output_root: '../'
pytorch_data_dir: '/home/fhoekstra/STEGO/dataloader_test/v2/cropped'
experiment_name: "exp1"
res: 200
batch_size: 16
num_workers: 16
run_picie: True
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False

model_paths:
  #- "../saved_models/cocostuff27_vit_base_5.ckpt"
  #- "../saved_models/cityscapes_vit_base_1.ckpt"
  # - "../saved_models/potsdam_test.ckpt"
  - "src/logs/checkpoints/stego_test_3/directory_exp1_date_Jun17_17-41-37/epoch=0-step=1199.ckpt"

hydra:
  run:
    dir: "/home/fhoekstra/STEGO/"
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
