output_root: 'logs'
pytorch_data_dir: '/storage/felix/Afstudeerproject/cropped/'
experiment_name: "carla_custom_1_clusterWarmup_L2_nclasses20"
log_dir: "stego_test_9"
azureml_logging: False
submitting_to_aml: False

# Loader params
num_workers: 32
max_steps: 15000
batch_size: 64

num_neighbors: 7
dataset_name: "directory"

# Used if dataset_name is "directory"
dir_dataset_name: "directory_five_crop_0.5"
dir_dataset_n_classes: 20

has_labels: False
crop_type: "five"
crop_ratio: .5
res: 200
loader_crop_type: "center"
cropping: False

# Model Params
extra_clusters: 0
use_true_labels: False
use_recalibrator: False
model_type: "vit_small"
arch: "dino"
use_fit_model: True
dino_feat_type: "feat"
projection_type: "nonlinear"
#projection_type: linear
dino_patch_size: 8
granularity: 1
continuous: True
dim: 64
dropout: True
zero_clamp: True

lr: 1e-4
pretrained_weights: ~
use_salience: False
stabalize: False
stop_at_zero: True

# Feature Contrastive params
pointwise: True
feature_samples: 30
neg_samples: 10
aug_alignment_weight: 0.0

correspondence_weight: 1.2


# IAROA vit small 1/31/22
# neg_inter_weight: 0.63
# pos_inter_weight: 0.25
# pos_intra_weight: 0.67

# neg_inter_shift: 0.46
# pos_inter_shift: 0.12
# pos_intra_shift: 0.18

# Potsdam vit small 1/31/22
#neg_inter_weight: 0.63
#pos_inter_weight: 0.25
#pos_intra_weight: 0.67
#neg_inter_shift: 0.46
#pos_inter_shift: 0.02
#pos_intra_shift: 0.08

# Cocostuff27 vit small 1/31/22
#neg_inter_weight: 0.63
#pos_inter_weight: 0.25
#pos_intra_weight: 0.67
#neg_inter_shift: 0.66
#pos_inter_shift: 0.02
#pos_intra_shift: 0.08


## Cocostuff27 10/3 vit_base

#neg_inter_weight: 0.1538476246415498
#pos_inter_weight: 1
#pos_intra_weight: 0.1
#
#neg_inter_shift: 1
#pos_inter_shift: 0.2
#pos_intra_shift: 0.12


## Cocostuff27 10/3 vit_small
# neg_inter_weight: .63
# pos_inter_weight: .25
# pos_intra_weight: .67

# neg_inter_shift: .16
# pos_inter_shift: .02
# pos_intra_shift: .08



## Cocostuff27 10/3 moco
#neg_inter_weight: .63
#pos_inter_weight: .25
#pos_intra_weight: .67
#
#neg_inter_shift: .26
#pos_inter_shift: .36
#pos_intra_shift: .32

#pos_inter_shift: .12
#pos_intra_shift: .18

## Cocostuff27
#neg_inter_weight: .72
#pos_inter_weight: .80
#pos_intra_weight: .29
#
#neg_inter_shift: .86
#pos_inter_shift: .04
#pos_intra_shift: .34

# Cityscapes 10/3

# neg_inter_weight: 0.9058762625226623
# pos_inter_weight: 0.577453483136995
# pos_intra_weight: 1

# neg_inter_shift: 0.31361241889448443
# pos_inter_shift: 0.1754346515479633
# pos_intra_shift: 0.45828472207


# Cityscapes
# neg_inter_weight: .72
# pos_inter_weight: .18
# pos_intra_weight: .46

# neg_inter_shift: .25
# pos_inter_shift: .20
# pos_intra_shift: .25

# Carla dataset weights and shifts (run ~14 july)
# neg_inter_weight: 0.72
# pos_inter_weight: 0.25
# pos_intra_weight: 0.67

# neg_inter_shift: 0.25
# pos_inter_shift: 0.15
# pos_intra_shift: 0.20

# rec_weight: 0.0
# repulsion_weight: 0.0
# lr: 5e-4
# Feature Contrastive params
# pointwise: True
# feature_samples: 11
# neg_samples: 5
# aug_alignment_weight: 0.0

# correspondence_weight: 1.0

# Carla dataset weights and shifts (run 1: 15 july)
# neg_inter_weight: 0.65
# pos_inter_weight: 0.30
# pos_intra_weight: 0.70

# neg_inter_shift: 0.30
# pos_inter_shift: 0.10
# pos_intra_shift: 0.15

# rec_weight: 0.1
# repulsion_weight: 0.05
# lr: 2e-4
# # Feature Contrastive params
# pointwise: True
# feature_samples: 15
# neg_samples: 7
# aug_alignment_weight: 0.0

# correspondence_weight: 1.2

# Carla dataset weights and shifts (run 2: 15 july)
# neg_inter_weight: 0.75
# pos_inter_weight: 0.25
# pos_intra_weight: 0.65
neg_inter_weight: 0.75
pos_inter_weight: 0.35
pos_intra_weight: 0.75

neg_inter_shift: 0.30
pos_inter_shift: 0.10
pos_intra_shift: 0.15

rec_weight: 0.1
repulsion_weight: 0.05
# lr: 2e-4
# # Feature Contrastive params
# pointwise: True
# feature_samples: 20
# neg_samples: 7
# dir_dataset_n_classes: [6, 9, 11, 14, 18, 23]
# aug_alignment_weight: 0.0

# correspondence_weight: 1.2


# CRF Params
crf_weight: 0.0
alpha: .5
beta: .15
gamma: .05
w1: 10.0
w2: 3.0
shift: 0.00
crf_samples: 1000
color_space: "rgb"

reset_probe_steps: ~

# Logging params
n_images: 5
scalar_log_freq: 10
checkpoint_freq: 50
val_freq: 100
hist_freq: 100


hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
